server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver

    url: postgres://kwofgxhzafzjxf:228fe6c8b43232e2efda5928d77fe45f579f2a0463bdf888ae756f26e4af2d51@ec2-52-86-25-51.compute-1.amazonaws.com:5432/doc545k5r24vb
    username: kwofgxhzafzjxf
    password: 228fe6c8b43232e2efda5928d77fe45f579f2a0463bdf888ae756f26e4af2d51
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
